# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://rm-gs5716in6yi04z055.mysql.singapore.rds.aliyuncs.com:3306/image_search?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: schnei_rds
    password: schnei@123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      max-active: 20
      min-idle: 5
      initial-size: 5
  redis:
    host: r-gs5mxemv6hsn5jdhi5.redis.singapore.rds.aliyuncs.com
    port: 6379
    password:
    timeout: 10000
    database: 0
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 1 # 连接池最小空闲连接
        max-wait: 1000 # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制


aliyun:
  image:
    endpoint: imagesearch.ap-southeast-1.aliyuncs.com
    region: ap-southeast-1
    accessKeyId: LTAIFmaxnrb5uGYd
    accessKeySecret: ZqTBZ5hYapEpAY7gNsP5EMQbK6beVQ
    instanceName: scimgsg1
  oss:
    bucketName: project-pixie
    endpoint: oss-ap-southeast-1.aliyuncs.com
    accessKeyId: LTAIFmaxnrb5uGYd
    accessKeySecret: ZqTBZ5hYapEpAY7gNsP5EMQbK6beVQ
  green:
    region: ap-southeast-1
    endpoint: green.ap-southeast-1.aliyuncs.com
    accessKeyId: LTAIFmaxnrb5uGYd
    accessKeySecret: ZqTBZ5hYapEpAY7gNsP5EMQbK6beVQ