# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

#redis:
#  host: 192.168.95.70
#  port: 6379
#  password: 123
#  timeout: 10000
#  timeBetweenEvictionRunsMillis: 30000 # 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
#  testOnBorrow: true # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
#  testWhileIdle: true # 在空闲时检查有效性, 默认false
#  database: 0
#  pool:
#    max-active: 1000 # 连接池最大连接数
#    max-idle: 10 # 连接池最大空闲连接
#    min-idle: 1 # 连接池最小空闲连接
#    max-wait: 1000 # 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
#    min-mvictable-idle-time-millis: 300000 # 连接的最小空闲时间 默认1800000毫秒(30分钟)