# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://rm-gs5716in6yi04z055.mysql.singapore.rds.aliyuncs.com:3306/image_search?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: schnei_rds
    password: schnei@123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      max-active: 20
      min-idle: 5
      initial-size: 5
  redis:
    host: r-gs5mxemv6hsn5jdhi5pd.redis.singapore.rds.aliyuncs.com
    port: 6379
    password: schnei@123
    timeout: 10000
  session:
    store-type: redis

aliyun:
  image:
    endpoint: imagesearch.ap-southeast-1.aliyuncs.com
    region: ap-southeast-1
    accessKeyId: C4DC59DA82CE17450F5B5847DFC4DAE1994A8164617B9EA516A8CF968DAF5D18
    accessKeySecret: A74186EEA31CC0E2214C46891AA11314B7F1628AF78928BF10259276CD5D7F13
    instanceName: scimgsg1
  oss:
    bucketName: project-pixie
    endpoint: oss-ap-southeast-1.aliyuncs.com
    accessKeyId: C4DC59DA82CE17450F5B5847DFC4DAE1994A8164617B9EA516A8CF968DAF5D18
    accessKeySecret: A74186EEA31CC0E2214C46891AA11314B7F1628AF78928BF10259276CD5D7F13
  green:
    region: ap-southeast-1
    endpoint: green-vpc.ap-southeast-1.aliyuncs.com
    accessKeyId: C4DC59DA82CE17450F5B5847DFC4DAE1994A8164617B9EA516A8CF968DAF5D18
    accessKeySecret: A74186EEA31CC0E2214C46891AA11314B7F1628AF78928BF10259276CD5D7F13